---
- name: reload apache
  service: name=apache2 state=reloaded
  
- name: drush cc drush
  command: drush cc drush
  register: drush_cc_drush_result
  failed_when: "drush_cc_drush_result.rc != 0"
  
- name: save iptables
  command: iptables-save
  sudo: true
  notify:
   - restart ufw
   
- name: restart ufw
  service: name=ufw state=restarted
  sudo: true
  
- name: restart mysql
  command: service mysql restart
  sudo: true
  changed_when: false
  
