---
# Drush 6 setup
# See "VLAD"[https://github.com/hashbangcode/vlad/blob/master/vlad/playbooks/roles/drupal/tasks/drush.yml]

- name: drush | install drush via composer and run it once
  shell: /usr/local/bin/composer global require --no-progress --no-interaction drush/drush:6.* -d /usr/share/composer; /usr/share/composer/vendor/bin/drush
  args:
    creates: /usr/share/composer/vendor/bin/drush
  sudo: true

- name: drush | make drush available globally
  file:
    src: /usr/share/composer/vendor/bin/drush
    dest: /usr/bin/drush
    state: link
    force: yes
  sudo: true

- name: drush | prepare user .drush directory
  file:
    path: /home/vagrant/.drush
    state: directory
    owner: "vagrant"
    group: "vagrant"
    recurse: yes

- name: drush | ensure previous drush directory is absent
  file:
    path: /home/vagrant/.composer/vendor/drush/
    state: absent

- name: drush | download the site audit module
  command: drush dl site_audit --destination=/home/vagrant/.drush/site_audit --yes
    creates=/home/vagrant/.drush/site_audit
  notify: drush cc drush

- name: drush | download the Coder module
  command: drush dl coder-7.x-2.x --destination=/home/vagrant/.drush/coder --yes
    creates=/home/vagrant/.drush/coder
  notify: drush cc drush

- name: drush | download the Registry Rebuild module
  command: drush dl registry_rebuild --destination=/home/vagrant/.drush/registry_rebuild --yes
    creates=/home/vagrant/.drush/registry_rebuild
  notify: drush cc drush

