---
# Needed for apt_repository below
- name: install dependencies
  apt: pkg=python-pycurl state=latest
  sudo: yes

# Regular apt-get would install an old version of Node that we don't want.
# This adds a more up to date repository and consequently a later version of Node.
- name: add up to date Node repository
  apt_repository: repo='ppa:chris-lea/node.js' state=present update_cache=yes
  sudo: true

- name: install Node
  apt: pkg=nodejs state=latest
  sudo: true

- name: install gulp.js
  command: 'npm install -g gulp'
  changed_when: False
  sudo: true
