---
- name: install php
  apt: name=php5 state=present

- name: Install required PHP packages.
  apt: name="{{ item }}" state=installed
  with_items: "{{ php_packages }}"
    
- name: Install the system PEAR package
  apt: name=php-pear state=present
  when: ansible_os_family == "Debian"
  
#- name: get phing channel and install phing

- name: Discover PEAR channels
  command: pear channel-discover {{ item }}
  with_items: pear_channels
  register: pear_channel_result
  changed_when: "'initialized' not in pear_channel_result.stdout"
  failed_when: "'failed' in pear_channel_result.stdout"

- name: Install PEAR packages
  command: pear install -alldeps {{ item }}
  with_items: pear_packages
  register: pear_package_result
  changed_when: "'is already installed' not in pear_package_result.stdout"
  failed_when:  "'No releases available for package' in pear_package_result.stdout"
  sudo_user: vagrant

#- name: Install PEAR phing package
#  command: "pear install --alldeps phing/phing"
#  sudo_user: vagrant
  
#- name: Install PEAR git package
#  command: "pear install VersionControl_Git-0.4.4"
#  sudo_user: vagrant

